### ISSUE TITLE
[bad-user-experience] Can you keep what I input in the text fields or warn me when I don't login in? 

### ISSUE THREAD

**Issue by legend80s** [ycjcl868/eslint-gpt#2]
很好的工具 👍🏻，但是有个缺点我辛辛苦苦填入了大量的示例 点击生成 出现登录弹窗，点击登录后一切都没有了 😒

能否保留在 localStorage 或提示用户填入的内容会被清除，请登录完毕后操作？

![image](https://user-images.githubusercontent.com/8603442/233882858-eb74ea7c-66d0-4798-9859-5e45393e2d35.png)

**Comment by ycjcl868** [comment]
Thanks，是个问题
